spring.application.name = edutainment-api-gateway
server.port=8090
#   EUREKA CONFIGURATION, O THIS SECTION WE NEED CONFIGURE THE SERVER EUREKA.
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.instance_id:${random.value}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

